//! PluginTrait definition. Every backend plugin must implement this trait and
//! export `_plugin_init` (auto-generated by `#[plugin_entry]`).

use crate::context::CoreContext;
use crate::events::{CoreEvent, PluginResponse};

/// Core FFI contract for backend plugins.
///
/// Implementations must be `Send + Sync` because they may be invoked from
/// different Tauri command threads.
pub trait PluginTrait: Send + Sync {
    /// Globally unique plugin id (reverse-DNS, e.g. `com.author.clock`).
    fn id(&self) -> &str;

    /// Called once when the plugin is enabled. Use `ctx` to register
    /// shortcuts, open windows, subscribe to events, etc.
    fn on_enable(&mut self, ctx: &mut CoreContext);

    /// Called when the plugin is disabled. Release resources here.
    fn on_disable(&mut self);

    /// Handle a Core event. Return `Some(response)` to send data back to Core.
    fn handle_event(&mut self, _event: CoreEvent) -> Option<PluginResponse> {
        None
    }
}
